[workspace]
members = [
    "crates/ocpm-core",
    "crates/ocpm-postgres",
    "crates/ocpm-python",
]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2024"
rust-version = "1.85"
authors = ["ocpm-engine contributors"]

[workspace.dependencies]
ocpm-core = { path = "crates/ocpm-core", version = "0.5.0" }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
