"""Standalone Rust-first object-centric process-mining engine."""

from . import _native as _native
from .analytics import (
    ConformanceScore,
    DriftContributor,
    DriftScore,
    PredictionScore,
    TransitionCount,
    bottleneck_order,
    dfg_conformance,
    frequency_drift,
    next_activity,
    variant_conformance,
)
from .bindings import (
    BindingCapsuleInfo,
    BindingPairGroup,
    BindingRow,
    binding_capsule_info,
    decode_binding_capsule,
    decode_binding_pair_groups,
)
from .engine import OcpmEngine, score_dynamic_dfg_rows
from .event_batches import (
    EventActivityCount,
    EventDfgEdge,
    EventLogExecution,
    EventLogSummary,
    EventVariantCount,
    summarize_event_batch_rows,
    summarize_event_window_batch_rows,
)
from .gnn import GnnBackend
from .gnn import require_backend as require_gnn_backend
from .models import (
    BindingIndexCoverage,
    BindingNeighborCoverage,
    BindingRelationCoverage,
    DynamicDfgRequest,
    DynamicFilter,
    EdgeFeature,
    EdgeFeatureExecution,
    EdgeFeatureRequest,
    EdgeFilter,
    Endpoint,
    EventAttributeFilter,
    EventLogRequest,
    EventLogWindow,
    LifecycleDfgExecution,
    LifecycleDfgRequest,
    LifecycleVariantExecution,
    LifecycleVariantRequest,
    NetworkFilter,
    PgOcpmCapabilities,
    ProcessMiningRequest,
    QueryPlan,
    WindowedDfgCount,
    WindowedVariantCount,
)
from .standalone import StandaloneEngine, serialize_model

__version__ = _native.__version__

__all__ = [
    "BindingIndexCoverage",
    "BindingNeighborCoverage",
    "BindingRelationCoverage",
    "EdgeFilter",
    "DynamicDfgRequest",
    "DynamicFilter",
    "EdgeFeature",
    "EdgeFeatureExecution",
    "EdgeFeatureRequest",
    "BindingCapsuleInfo",
    "BindingPairGroup",
    "BindingRow",
    "Endpoint",
    "EventAttributeFilter",
    "EventActivityCount",
    "EventDfgEdge",
    "EventLogExecution",
    "EventLogRequest",
    "EventLogSummary",
    "EventLogWindow",
    "LifecycleDfgExecution",
    "LifecycleDfgRequest",
    "LifecycleVariantExecution",
    "LifecycleVariantRequest",
    "EventVariantCount",
    "GnnBackend",
    "NetworkFilter",
    "OcpmEngine",
    "StandaloneEngine",
    "serialize_model",
    "ProcessMiningRequest",
    "PgOcpmCapabilities",
    "QueryPlan",
    "WindowedDfgCount",
    "WindowedVariantCount",
    "ConformanceScore",
    "DriftContributor",
    "DriftScore",
    "PredictionScore",
    "TransitionCount",
    "bottleneck_order",
    "binding_capsule_info",
    "decode_binding_capsule",
    "decode_binding_pair_groups",
    "dfg_conformance",
    "frequency_drift",
    "next_activity",
    "require_gnn_backend",
    "score_dynamic_dfg_rows",
    "summarize_event_batch_rows",
    "summarize_event_window_batch_rows",
    "variant_conformance",
    "__version__",
]
